version: '3'
services:
  #Database
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_TCP_PORT: 13900
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: oussama
      MYSQL_PASSWORD: admin
    networks:
      - wpsite
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db:13900
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - wpsite
  #WORDPRESS
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.3
    ports:
      - 9999:80
    restart: always
    volumes: 
          - ./site:/var/www/html/
          - ./plugins:/var/www/html/wp-content/plugins
          - ./themes:/var/www/html/wp-content/themes
    environment:
      WORDPRESS_DB_HOST: db:13900
      WORDPRESS_DB_USER: oussama
      WORDPRESS_DB_PASSWORD: admin
    networks:
      - wpsite
  #CLI    
  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:9999" --title="Local Wordpress By Docker" --admin_user=oussama --admin_password=admin --admin_email=oussamabekbich@gmail.com
      '
    #Theme and plugin mapped localy
    volumes:
      - ./site:/var/www/html/
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      
networks:
  wpsite:
volumes:
  db_data:
